# Generated by Django 5.2.9 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingouser',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bingoevent',
            name='background_file',
            field=models.FileField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='bingoevent',
            name='theme_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
