# Generated by Django 5.2.9 on 2025-12-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bingoevent_event_title_playlisttrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingoevent',
            name='primary_color',
            field=models.CharField(default='#3f51b5', max_length=7),
        ),
    ]
