# Generated by Django 5.2.9 on 2026-03-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_theme_customization_and_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bingoevent',
            name='platform',
            field=models.CharField(default='spotify', max_length=20),
        ),
        migrations.AddField(
            model_name='bingouser',
            name='premium_trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
