# Generated by Django 5.2.9 on 2025-12-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bingoevent_primary_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'ordering': ['track_name']},
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='artist_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='played',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='track_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
