# Generated by Django 5.2.9 on 2025-12-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_playlisttrack_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='playlisttrack',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='playlisttrack',
            name='track_name',
        ),
    ]
