# Generated by Django 5.2.9 on 2026-01-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_playlisttrack_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingoevent',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
