# Generated by Django 5.2.9 on 2026-01-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bingoevent_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingoevent',
            name='orientation',
            field=models.CharField(default='portrait', max_length=10),
        ),
    ]
